{
 "title": "influxdb",
 "time": { "from": "2021-03-29T16:21:37.141Z", "to": "2021-03-29T16:28:54.356Z" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "memory usage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 20, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cpu usage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "/boot",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sda1" }
     ]
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 11, "y": 20 },
   "targets": [
    {
     "alias": "cpu usage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "disk usage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "overlay" }
     ]
    }
   ]
  }
 ]
}